channels:
  - defaults

dependencies:
  - pip>=20.3.3
  - python=3.10
  - pip:
      - numpy>=1.20
      - matplotlib>=3.4
      - scipy>=1.8
      - corner
      - astropy
      - astroquery
      - jax
      - jaxopt
      - jax_cosmo
      # My packages:
      - pyia
      - git+https://github.com/adrn/gala
      # This code:
      - .
      # Jupyter:
      - jupyter
      - notebook
      - jupytext